/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ed6f14fd-4d18-42cc-9094-bba6e52686c8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_D6zruwaAg",
    "aws_user_pools_web_client_id": "1q2cg7ubr5n0a2bdc8lpu8rbi0",
    "oauth": {},
    "aws_user_files_s3_bucket": "bookbucket183837-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
